name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'public/**'
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.js'
      - 'index.html'
      - 'postcss.config.js'
      - '.eslintrc.js'
      - '.browserlistrc'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VITE_PORT: ${{ vars.VITE_PORT }}
      VITE_API_POSTS: ${{ vars.VITE_API_POSTS }}
      VITE_API_REFS: ${{ vars.VITE_API_REFS }}
      VITE_API_CODES: ${{ vars.VITE_API_CODES }}
      VITE_API_PROJECTS: ${{ vars.VITE_API_PROJECTS }}
      VITE_OG_TITLE: ${{ vars.VITE_OG_TITLE }}
      VITE_OG_URL: ${{ vars.VITE_OG_URL }}
      VITE_OG_IMAGE: ${{ vars.VITE_OG_IMAGE }}
      VITE_OG_DESCRIPTION: ${{ vars.VITE_OG_DESCRIPTION }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Trigger deployment webhook
      if: success()
      run: |
        # Create the payload
        PAYLOAD='{
          "ref": "refs/heads/main",
          "repository": {
            "name": "${{ github.repository }}",
            "full_name": "${{ github.repository }}"
          },
          "head_commit": {
            "id": "${{ github.sha }}",
            "message": "${{ github.event.head_commit.message }}"
          }
        }'

        # Calculate signatures with both secrets for comparison
        SIGNATURE_GITHUB=$(echo -n "$PAYLOAD" | openssl dgst -sha1 -hmac "${{ secrets.DEPLOY_WEBHOOK_SECRET }}" | cut -d' ' -f2)

        # Send the webhook with signature and verbose output
        curl -v -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -H "X-Hub-Signature: sha1=$SIGNATURE_GITHUB" \
          -d "$PAYLOAD"
