name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'public/**'
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.js'
      - 'index.html'
      - 'postcss.config.js'
      - '.eslintrc.js'
      - '.browserlistrc'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_PORT: ${{ vars.VITE_PORT }}
      VITE_API_POSTS: ${{ vars.VITE_API_POSTS }}
      VITE_API_REFS: ${{ vars.VITE_API_REFS }}
      VITE_API_CODES: ${{ vars.VITE_API_CODES }}
      VITE_API_PROJECTS: ${{ vars.VITE_API_PROJECTS }}
      VITE_OG_TITLE: ${{ vars.VITE_OG_TITLE }}
      VITE_OG_URL: ${{ vars.VITE_OG_URL }}
      VITE_OG_IMAGE: ${{ vars.VITE_OG_IMAGE }}
      VITE_OG_DESCRIPTION: ${{ vars.VITE_OG_DESCRIPTION }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Create archive of dist folder
      run: tar -czf dist.tar.gz -C dist .

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "dist.tar.gz"
        target: "/tmp/"

    - name: Extract and move files to deployment directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          # Create the deployment directory if it doesn't exist
          mkdir -p ${{ secrets.DEPLOY_PATH }}

          # Navigate to the deployment directory
          cd ${{ secrets.DEPLOY_PATH }}

          # Remove existing content
          rm -rf *

          # Extract the archive directly into the deployment directory
          tar -xzf /tmp/dist.tar.gz -C .

          # Change ownership of extracted files to www-data
          chown -R www-data:www-data .

          # Make deploy script executable and execute it
          chmod +x ${{ secrets.DEPLOY_SCRIPT }}
          bash ${{ secrets.DEPLOY_SCRIPT }}

          # Clean up temporary archive
          rm -f /tmp/dist.tar.gz
